eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka


server:
  port: 8070
spring:
  application:
    name: loyalty-service
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/schools
#    username: username
#    password: password
  datasource:
    url: jdbc:h2:mem:loyalty-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888